# Uncomment the next line to define a global platform for your project
platform :ios, '14.7'

target 'ios-simple-objc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-simple-objc

  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'ios-simple-objcTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
